apiVersion: apps/v1
kind: Deployment
metadata:
  name: db01
  labels:
    app: db01
spec:
  selector:
    matchLabels:
      app: db01
  replicas: {{ .Values.db.replicas }}
  template:
    metadata:
      labels:
        app: db01
    spec:
      volumes:
       - name: db-backup
         hostPath:
            path: /mnt/data
      containers:
      - name: db01
        image: {{ .Values.db.container.image }}
        ports:
        - name: db01-port
          containerPort: {{ .Values.db.container.port }}
        volumeMounts:  
          - name: db-backup
            mountPath: "/var/lib/mysql"
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: {{ .Values.db.container.pswd }}
        
          
